[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pyth_oracle_1 = "2UA3M6dSJQjrfTdzAiL2vMvubWoch1nTXK5TRaNGuiY4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
